/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment4;
import com.Student;
import com.Teacher;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String args[])
    {
          	EntityManagerFactory factory=Persistence.createEntityManagerFactory("PracticePU");
          	EntityManager manager=factory.createEntityManager();
          	
          	
          	Student obj=new Student();
          	obj.setStudentName("Peter");
          	obj.setSemester("2nd");
          	manager.getTransaction().begin();
          	manager.flush();
            manager.getTransaction().commit();
           
    }
}