/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignment3;
import javax.persistence.EntityManager;



import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.PassengerId;
import com.Passenger;

public class Library {
EntityManager entityManager;
    
    public Library() {
    	EntityManagerFactory factory=Persistence.createEntityManagerFactory("CustomerPU");
    	entityManager=factory.createEntityManager();
    }
    
    public void savePassenger(Passenger passenger) {
		entityManager.getTransaction().begin();
		entityManager.persist(passenger);
		entityManager.flush();
		entityManager.getTransaction().commit();
    }
    
    public void savePassengerId(PassengerId passengerId) {
		entityManager.getTransaction().begin();
		entityManager.persist(passengerId);
		entityManager.flush();
		entityManager.getTransaction().commit();
	
    }
    public static void main(String[] args) {
		PassengerId passengerId = new PassengerId();
		passengerId.setPassengerEmail("kidharvinodh198@gmail.com");
		passengerId.setPassengerMobile(9283391839l);
		
		Passenger passenger = new Passenger();
		passenger.setPassengerEmail(passenger.getPassengerEmail());
		passenger.setPassengerMobile(passenger.getPassengerMobile());
		passenger.setPassengerName("Vinodh Kumar");
		passenger.setSource("Tanuku");
		passenger.setDestination("Samalarkot");
		Library lib=new Library();
		lib.savePassenger(passenger);
		lib.savePassengerId(passengerId);
		
		
	}
}
